### PR TITLE
 Make it possible to /janame remote snitches (#48) 

### LINKED ISSUE #48: Add a mass-rename command
By @Ameliorate https://www.reddit.com/r/civclassics/comments/6lt7cs/changelog_for_772017/djxf84f/

> I've been thinking of implementing a mass-rename command in JukeAlert that renames any snitch with a given pattern in it's name, even if you aren't near it.
`/jamassrename [GROUP] [REGEX] [REPLACE]`
For example, `/jamassrename IllegalSnitchNetwork ^\[ISN] [LegalSN]` would rename `[ISN]ZeroZero` to `[LegalSN]ZeroZero`.
Is this something I should put effort into?
I might implement a separate mode to use textual replace instead of a regex, but that's mostly an implementation detail.

This feature would absolutely have to support undo functionality.

### PR DESCRIPTION
**Pull request by awoo-civ**
Sort-of fixes https://github.com/DevotedMC/JukeAlert/issues/48

Also fixes an issue where you wouldn't get any response when attempting to /janame without having a valid snitch nearby. Now an error message is present.

Tested:
 * Perms work for both options
 * Argument parsing works and fails for invalid ones
 * Default world argument works
 * Works the same way it used to if only a name is specified

### CODE REVIEW

**Comment by DevotedServant** [comment]
Can one of the admins verify this patch? @ProgrammerDan @Maxopoly

"ok to test" will build any commits made to this PR
"test this please" will build this PR once
"retest this please" will make another single build for this PR
"add to whitelist" will whitelist the creator of this PR and make jenkins automatically build any PRs made by him

**Comment by Maxopoly** [comment]
ok to test

**Comment by awoo-civ** [comment]
Implemented fixes as suggested by @Maxopoly 👍

**Comment by ProgrammerDan** [comment]
ok to test

**Pull request merged**
