### PR TITLE
Add events for snitch login/logout

### PR DESCRIPTION
**Pull request by Maxopoly**

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
ok to build

**Comment by ProgrammerDan** [comment]
So uh, what uses these events

**Comment by Gjum** [comment]
They're used by Kira, CivClassic's Discord/API bot: https://github.com/Maxopoly/KiraBukkitGateway/blob/master/src/main/java/com/github/maxopoly/KiraBukkitGateway/listener/JukeAlertListener.java

**Comment by ProgrammerDan** [comment]
Oh! Ok, cool.

**Pull request merged**
