### PR TITLE
Add compass direction and distance to snitch messages

### PR DESCRIPTION
**Pull request by okx-code**
image

This PR adds compass driection with 8 points and a distance to snitch messages. It also makes snitch messages configurable so server owners can change this if they wish.

### CODE REVIEW

**Comment by DevotedServant** [comment]
Can one of the admins verify this patch? @ProgrammerDan @Maxopoly

"ok to test" will build any commits made to this PR
"test this please" will build this PR once
"retest this please" will make another single build for this PR
"add to whitelist" will whitelist the creator of this PR and make jenkins automatically build any PRs made by him

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
Looks like problems are just javadoc ones. 
Noticing a few extra commits, do you expect this PR is complete?

**Comment by okx-code** [comment]
Yes, this PR is complete, those commits are for another PR. I want to keep different features in different PRs.

**Comment by ProgrammerDan** [comment]
Looks good, thanks.

**Pull request merged**
