### PR TITLE
Add /jalistlong

### PR DESCRIPTION
**Pull request by awoo-civ**
There's a possibility that this compiles!

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Be sure to add the command to https://github.com/DevotedMC/JukeAlert/blob/master/src/main/resources/plugin.yml and increment the build version in the root pom.xml file.

**Comment by ProgrammerDan** [comment]
Much better. I'll check it over and buildtest later.

**Comment by ProgrammerDan** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.835 s
[INFO] Finished at: 2016-12-20T21:19:53-05:00
[INFO] Final Memory: 18M/395M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project JukeAlert: Compilation failure: Compilation failure:
[ERROR] /C:/Programming/Minecraft/jukealert/src/main/java/com/untamedears/JukeAlert/command/JukeAlertCommandHandler.java:[10,50] cannot find symbol
[ERROR] symbol:   class JaListLongCommand
[ERROR] location: package com.untamedears.JukeAlert.command.commands
[ERROR] /C:/Programming/Minecraft/jukealert/src/main/java/com/untamedears/JukeAlert/command/JukeAlertCommandHandler.java:[24,33] cannot find symbol
[ERROR] symbol:   class JaListLongCommand
[ERROR] location: class com.untamedears.JukeAlert.command.JukeAlertCommandHandler
[ERROR] /C:/Programming/Minecraft/jukealert/src/main/java/com/untamedears/JukeAlert/tasks/GetSnitchListPlayerTask.java:[23,13] cannot find symbol
[ERROR] symbol: variable truncateName
[ERROR] /C:/Programming/Minecraft/jukealert/src/main/java/com/untamedears/JukeAlert/tasks/GetSnitchListPlayerTask.java:[28,100] cannot find symbol
[ERROR] symbol:   variable truncateName
[ERROR] location: class com.untamedears.JukeAlert.tasks.GetSnitchListPlayerTask
[ERROR] -> [Help 1]
```
Brought to you by your neighborhood friendly build-service

**Comment by awoo-civ** [comment]
Part 2: https://github.com/DevotedMC/JukeAlert/pull/11

**Pull request closed without merging**
